import { nanoid } from 'nanoid';
import { EBlogPostLanguage } from 'src/i18n/utils';

export const posts = [
  {
    id: nanoid(),
    title: 'Drag-and-drop на JavaScript быстро',
    highlight: "Разбираемся в drag-and-drop'e на JavaScript - быстро, без лишней воды, всяких библиотек и прочего",
    link: 'javascript-drag-and-drop-quickly',
    category: 'tutorial',
    date: '25 dec 2025',
    tags: ['javascript'],
    language: EBlogPostLanguage.RU,
  },
  {
    id: nanoid(),
    title: 'Время зажигать звёзды 💫',
    highlight: 'Делаем анимированную звезду с помощью CSS и JavaScript',
    link: 'animated-star-tutorial',
    category: 'tutorial',
    date: '10 oct 2025',
    tags: ['react', 'css', 'javascript'],
    language: EBlogPostLanguage.RU,
  },
  {
    id: nanoid(),
    title: 'How to create a page scroll progress bar',
    highlight:
      'In this quick tutorial you will learn how to create a simple scroll progress bar using React step by step',
    link: 'how-to-create-a-page-scroll-progress-bar',
    category: 'tutorial',
    date: '29 apr 2024',
    tags: ['react'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'My favorite websites to improve English',
    highlight: 'English learning web tools I can not live without',
    link: 'my-favorite-websites-to-improve-english',
    category: 'insight',
    date: '24 apr 2024',
    tags: ['english'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'How I improved my English',
    highlight: 'Tips that helped me and that can help you to improve your English level',
    link: 'how-i-improved-my-english',
    category: 'insight',
    date: '28 dec 2022',
    tags: ['english'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'Keep calm and test',
    highlight: 'If you need a sign to start testing your React applications, this is it',
    link: 'keep-calm-and-test',
    category: 'tutorial',
    date: '16 dec 2022',
    tags: ['react', 'typescript', 'jest', 'testing'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'Pure CSS toggle switch',
    highlight: 'A step-by-step tutorial how to create a toggle switch using only HTML and CSS without using JavaScript',
    link: 'pure-css-toggle-switch',
    category: 'tutorial',
    date: '1 oct 2022',
    tags: ['html', 'css'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'Gerund VS Infinitive',
    highlight: 'Check out this small lesson to know what are gerunds and infinitives and how do you use them',
    link: 'gerund-vs-infinitive',
    category: 'english',
    date: '27 sep 2022',
    tags: ['english'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'Semantic markup for the little ones',
    highlight: 'What is semantic markup and why should you write it?',
    link: 'semantic-markup-for-the-little-ones',
    category: 'guide',
    date: '23 sep 2022',
    tags: ['html'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'How to improve your skills',
    highlight:
      "If you feel that you're stuck in a rut or just need some fresh inspiration how to enhance your skills there are ways you can do to help achieve this goal",
    link: 'how-to-improve-your-skills',
    category: 'insight',
    date: '2 sep 2022',
    tags: ['skills'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'Drag and drop',
    highlight: 'A guide to implementing drag and drop in React app without using any third party libraries',
    link: 'drag-and-drop',
    category: 'tutorial',
    date: '1 sep 2022',
    tags: ['React'],
    language: EBlogPostLanguage.ENG,
  },
  {
    id: nanoid(),
    title: 'Pure CSS tooltips',
    highlight:
      'A step-by-step tutorial that will show you how to create a tooltip using only CSS without any additional JavaScript code',
    link: 'pure-css-tooltips',
    category: 'tutorial',
    date: '30 jul 2022',
    tags: ['HTML', 'CSS'],
    language: EBlogPostLanguage.ENG,
  },
];
